-

diff --git a/cloudbuild/cloudbuild.yaml b/cloudbuild/cloudbuild.yaml
--- a/cloudbuild/cloudbuild.yaml
+++ b/cloudbuild/cloudbuild.yaml
@@ -55,7 +55,16 @@ steps:
         - |
           source build_vars &&
           apt-get update -y;apt-get install -y jq curl &&
-          $$LOCAL_REPO_DIR/files/repoScan.sh
+          ./twistcli coderepo scan --address $TL_CONSOLE --details -u $TL_USER -p $TL_PASS "/workspace/anthos-gke-hybrid-prismacloud/app" &&
+          result=$("curl -k -u $TL_USER:$TL_PASS -H 'Content-Type: application/json' $TL_CONSOLE/api/v1/coderepos-ci?limit=1&reverse=true&sort=scanTime"|jq '.[0].pass') &&
+          if [ "$result" = "true" ] || [ "$BYPASS_REPOSCAN" = "1" ]; then
+            echo "Code Repo scan passed!"
+          exit 0
+          else
+            echo "Code Repo scan failed!"
+          exit 1
+          fi
+#          $$LOCAL_REPO_DIR/files/repoScan.sh
         secretEnv: ['TL_USER', 'TL_PASS', 'TL_CONSOLE']
 
       - id: OSS License Check 
